#!/bin/sh

gem install /tmp/bundler-1.7.3.gem --local --no-rdoc --no-ri

# Overwrite the unicorn.rb used by heroku.
mkdir -p /usr/share/horizon/pids

adduser --system horizon
chown -R horizon /usr/share/horizon
